name: CI

on:
  push:
    branches: [ master ]
    
env:
  BUCKET: node-59554.appspot.com

jobs:
   build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Vai rodar o instalador do nodejs
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: instalando dependencia Yarn
      run: yarn install
      
    - name: Build
      run: yarn build
    
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        project_id: ${{ secrets.GCP_PROJECT}}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
        
    - name: Upload dos arquivos para o gcloud
      run: gsutil -m rsync -R ./build gs://"$BUCKET"
    
    - name: Dando acesso publico aos arquivos
      run: gsutil -m acl ch -R -u AllUsers:R gs://"$BUCKET"
      
    - name: Cache de imagens
      run: gstuil setmeta -h "Cache-Control:public, max="23813813123" gs://"$BUCKET"/**/*.{png,svg,css,js}
    
    - name: Cache de dados
      run: gsutil setmeta -h "Cache-Control:no-cache, no-store" gs://"$BUCKET"/index.html
